### PR TITLE
Auth -edit profile-fetch

### PR DESCRIPTION
**Pull request by Abhijeet43**
- User Can Login/SignUp and Logout
- User can see posts related to his followers on home page
- User can see all posts on explore page
- Likes and Comments count are working fine 
- User can view and edit profile details on profile page
- User can view his own posts on profile page
* Note: 
    - Bookmarks page won't work currently 
    - Profile Picture in user-post won't get updated(this will be handled in upcoming PRs)
    - Site is currently not responsive

### CODE REVIEW

**Review by vermasavita — COMMENTED** [review]
- Check toast message "Password & Confirm Password not match" 
- After sign-up, user see black page. There is some bug in signup or home page functionality I guess

- It's strange, but your preview is not working now. Please check

**Review by vermasavita — APPROVED** [review]
- remove border for main section. 
- Rest looks good to me. Approving

**Review by RanjeetKumar12 — APPROVED** [review]
- Clean and readable code with good file structure
- will suggest refactoring some of lengthy components
- Adding responsiveness will be great as your pages aren't scaling relative to my screen width.. Good to merge

**Comment by Abhijeet43** [comment]
> * Clean and readable code with good file structure
> * will suggest refactoring some of lengthy components
> * Adding responsiveness will be great as your pages aren't scaling relative to my screen width.. Good to merge

As mention in the note above..Site is currently not responsive... Responsiveness will be taken care in upcoming PRs

**Pull request merged**
